# Generated by Django 4.2.13 on 2024-06-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Body',
            new_name='body',
        ),
    ]
